---
title: Assignment B-1
author: Grace Melchers
course: STAT 545B 2023
output: github_document
---

# Exercise 1 & 2: Making a function and documenting it

```{r}
# Exercise 1: Making the function

## Step 1: Load the necessary packages

library(tidyverse)
library(datateachr)
library(testthat)
library(roxygen2)

## Step 2: Write the function
## In my Mini Data Analysis, I often needed counts by neighborhood of different observations and also their values, for example the number of trees in one neighborhood or the mean, standard deviation and range of values for diameter within a certain neighborhood. I will create a function that allows me to instantly calculate all of these values within a grouped categorical variable for a numeric variable.

summarize_obs_by_var_group <- function(df, grouped_var, summarized_var, na.rm = TRUE) {
  
  grouped_var_a <- deparse(substitute(grouped_var))
  summarized_var_a <- deparse(substitute(summarized_var))
  if(!is.character(df[[grouped_var_a]])) {
    stop('Sorry, grouped_var can only be a character vector')
  }
  if(!is.numeric(df[[summarized_var_a]])) {
    stop('Sorry, summarized_var can only be a numeric vector')
  }
  df |>
    group_by({{grouped_var}}) |>
    summarize(n = n(), mean = mean({{summarized_var}}), stdev = sd({{summarized_var}}), range = (max({{summarized_var}}) - min({{summarized_var}})))
}

# Exercise 2: Document function

#' Summarize Observations by Another Variable's Category
#' 
#' Description: This function calculates a summary (count of observations, mean, standard deviation, range of values) of the observations for a specific variable by each group in that variable.
#' @param grouped_var A character vector. I named this grouped_var because this is the variable that the function will use the group_by function with to group observations by the different categories within that variable.
#' @param summarized_var A numeric vector, a number. I named this summarized_var because this is the variable that the function will summarize with a count of it's observations, it's mean, standard deviation and range, based on the grouped categories of the grouped_var variable.
#' @return A dataframe with a count of the number of observations of one variable grouped by the categories of another variable.
#' @examples
#' summarize_obs_by_var_group(vancouver_trees, neighbourhood_name, diameter)
#' summarize_obs_by_var_group(steam_games, developer, original_price)

```

# Exercise 3: Examples

```{r}

# I will demonstrate several examples of this function using a few different datasets.

# First, we will get a summary of the diameter of trees found in different neighbourhoods in the City of Vancouver using the vancouver_trees dataset from datateachr. I worked with this dataset for the MDA and questions like this one are what prompted me to create this function.

summarize_vancouver_nbhd_diam <- summarize_obs_by_var_group(vancouver_trees, neighbourhood_name, diameter)

summarize_vancouver_nbhd_diam

# Another example can be used with the steam_games dataset also from the datateachr package. Here, we will get the summary stats for original price of games grouped by developer.

summarize_games_developer_price <- summarize_obs_by_var_group(steam_games, developer, original_price)

summarize_games_developer_price

# Let's show an example of when the function will throw an error - in this case, we will use the vancouver_trees dataset again to show how if we input a variable consisting of character vectors as the summarized_var, it will provide an error message and won't work. We will use neighbourhood_name as the grouped_var and std_street as the summarized_var, which is a character vector, not a numerical one.

summarize_vancouver_nbhd_street <- summarize_obs_by_var_group(vancouver_trees, neighbourhood_name, std_street)

summarize_vancouver_nbhd_street

```

# Exercise 4: Testing the function

```{r}

# Let's test our function using the first example above with the output of summarize_vancouver_nbhd_diam. This should work properly, so let's use the testthat package to determine if this is the case.

test_that('Function works with vancouver_trees',
  expect_equal(summarize_vancouver_nbhd_diam, (vancouver_trees |>
                                                 group_by(neighbourhood_name) |>
                                                  summarize(n = n(), mean = mean(diameter), stdev = sd(diameter), range = (max(diameter) - min(diameter))))))

# For our second test, let's test that the function is throwing the proper error in the proper scenario - in this case, when we try to input a variable with a character vector as the summarized_var using the vancouver_trees dataset again.

test_that('Function throws expected error with vancouver_trees', expect_error(summarize_obs_by_var_group(vancouver_trees, neighbourhood_name, std_street), 'Sorry, summarized_var can only be a numeric vector'))

# For our third and last test, we will ensure that the output type of the function matches what we expect it to be using an example from earlier that I created from the steam_games dataset, the output summarize_games_developer_price.

test_that('Function produces a dataframe',
          expect_type(summarize_games_developer_price, "list"))

```

